@host = http://localhost
@port = 3100
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzdWFyaW8iOjEsIm1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwZXJmaWwiOiJhZG1pbiIsImlhdCI6MTYzNTQyMTU3NywiZXhwIjoxNjM1NDI1MTc3fQ.vXjMRU_SMBSVwb_7--JkzTWesxwjL1jVzfN5pM6YyEI


### Create
POST {{host}}:{{port}}/api/registro/create
content-type: application/json
authorization: type {{token}} 

{
"idvacina": 3,
"data": "2020-01-23"
}



### Lista
GET {{host}}:{{port}}/api/registro/lista
authorization: type {{token}} 



### Update data
PUT {{host}}:{{port}}/api/registro/update/data
authorization: type {{token}} 
content-type: application/json

{
"idusuario": 2,
"idregistro": 22,
"data": "2021-10-19"
}




### Update idvacina
PUT {{host}}:{{port}}/api/registro/update/idvacina
authorization: type {{token}} 
content-type: application/json

{
"idregistro": 9,
"idvacina": 1
}




### Delete
DELETE  {{host}}:{{port}}/api/registro/delete/23
authorization: type {{token}} 
