@host = http://localhost
@port = 3100
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzdWFyaW8iOjEsIm1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwZXJmaWwiOiJhZG1pbiIsImlhdCI6MTYzNTQyMTU3NywiZXhwIjoxNjM1NDI1MTc3fQ.vXjMRU_SMBSVwb_7--JkzTWesxwjL1jVzfN5pM6YyEI


### Create
POST {{host}}:{{port}}/api/vacina/create
content-type: application/json
authorization: type {{token}} 

{
"nome": "Vacina B3"
}



### Update nome
PUT {{host}}:{{port}}/api/vacina/update/nome
content-type: application/json
authorization: type {{token}} 

{
"idvacina": 5,
"nome": "Vacina E"
}




### Delete
DELETE {{host}}:{{port}}/api/vacina/delete/14
authorization: type {{token}} 




### Lista
GET {{host}}:{{port}}/api/vacina/lista
authorization: type {{token}} 
